// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RTL.TVMaze.Data.Mapping;

namespace RTL.TVMaze.Data.Migrations
{
    [DbContext(typeof(RTLContext))]
    partial class RTLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RTL.TVMaze.Data.Models.Cast", b =>
                {
                    b.Property<int>("ID");

                    b.Property<DateTime?>("Birthday");

                    b.Property<string>("Name");

                    b.Property<int>("TVShowId");

                    b.Property<DateTime>("Updated");

                    b.HasKey("ID");

                    b.HasIndex("TVShowId");

                    b.ToTable("Cast");
                });

            modelBuilder.Entity("RTL.TVMaze.Data.Models.TVShow", b =>
                {
                    b.Property<int>("ID");

                    b.Property<string>("Name");

                    b.Property<DateTime>("Updated");

                    b.HasKey("ID");

                    b.ToTable("TVShow");
                });

            modelBuilder.Entity("RTL.TVMaze.Data.Models.Cast", b =>
                {
                    b.HasOne("RTL.TVMaze.Data.Models.TVShow", "TVShow")
                        .WithMany()
                        .HasForeignKey("TVShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
